/**
 * Fraud review email templates (FRAUD_DETECTION_SQL.MD Task 2).
 */

import { PlainTextEmailService } from '@/src/lib/plain-text-email-service';

const FOUNDER_SIGNATURE = `Justice Asibe
Founder and CEO, SoundBridge Live Ltd
justice@soundbridge.live
soundbridge.live`;

export type FraudEmailTemplateType = 'payout_withheld' | 'warning_monitoring';

export function buildPayoutWithheldEmail(params: {
  creatorName: string;
  trackTitle: string;
  playCount: number;
}): { subject: string; text: string; templateType: FraudEmailTemplateType } {
  const { creatorName, trackTitle, playCount } = params;
  return {
    templateType: 'payout_withheld',
    subject: 'Important Notice | Your SoundBridge Payout',
    text: `Hi ${creatorName},

We are writing regarding your track ${trackTitle} which has recorded ${playCount.toLocaleString()} plays on SoundBridge.

During our routine payout review we identified a number of anomalies in the play data for this track that are inconsistent with organic listening behaviour. Specifically the plays were generated by a very small number of unique listeners and IP addresses which suggests the play count may not reflect genuine audience engagement.

As a result we are withholding your payout for this period while we complete our review.

If you believe this is an error and can provide a legitimate explanation for the play activity on this track please reply to this email within 5 working days with any relevant information.

Please note that artificially inflating play counts is a violation of SoundBridge's Terms of Service and may result in account suspension.

We take the integrity of our platform seriously and want to ensure that all creators are rewarded fairly for genuine audience engagement.

We look forward to hearing from you.

${FOUNDER_SIGNATURE}`,
  };
}

export function buildWarningMonitoringEmail(params: {
  creatorName: string;
  trackTitle: string;
}): { subject: string; text: string; templateType: FraudEmailTemplateType } {
  const { creatorName, trackTitle } = params;
  return {
    templateType: 'warning_monitoring',
    subject: 'Platform Notice | Play Activity on Your Track',
    text: `Hi ${creatorName},

We are writing regarding your track ${trackTitle} on SoundBridge.

During a routine review of platform activity we noticed that the play count for this track shows an unusually high ratio of plays to unique listeners. While we are not taking any action at this time we wanted to make you aware that we monitor all play activity on the platform to ensure fairness for every creator in our community.

Please ensure that your play activity reflects genuine audience engagement. Artificially inflating play counts through any means is a violation of SoundBridge's Terms of Service and may result in withheld payouts or account suspension.

If you have any questions or concerns please do not hesitate to reach out.

${FOUNDER_SIGNATURE}`,
  };
}

export function fraudEmailTemplateForStatus(
  fraudStatus: string | null | undefined,
  params: { creatorName: string; trackTitle: string; playCount: number },
): { subject: string; text: string; templateType: FraudEmailTemplateType } {
  if (fraudStatus === 'hold') {
    return buildPayoutWithheldEmail(params);
  }
  return buildWarningMonitoringEmail(params);
}

export async function sendCustomFraudReviewEmail(params: {
  to: string;
  subject: string;
  text: string;
}): Promise<boolean> {
  return PlainTextEmailService.sendPlainTextEmail({
    to: params.to,
    from: process.env.SENDGRID_FROM_EMAIL || 'contact@soundbridge.live',
    fromName: 'Justice Asibe — SoundBridge',
    subject: params.subject,
    text: params.text,
  });
}

/** @deprecated Use sendCustomFraudReviewEmail with buildPayoutWithheldEmail */
export async function sendFraudPayoutWithheldEmail(to: string, creatorName: string): Promise<boolean> {
  const { subject, text } = buildPayoutWithheldEmail({
    creatorName,
    trackTitle: 'your track',
    playCount: 0,
  });
  return sendCustomFraudReviewEmail({ to, subject, text });
}

export async function sendFraudAccountBannedEmail(to: string, creatorName: string): Promise<boolean> {
  return PlainTextEmailService.sendPlainTextEmail({
    to,
    subject: 'Important: Your SoundBridge account has been suspended',
    text: `Hi ${creatorName},

Your account has been suspended due to a violation of our platform terms regarding play count integrity.

If you believe this is an error, contact contact@soundbridge.live.

${FOUNDER_SIGNATURE}`,
  });
}
